version: '3.3'

services:
  weather-app:
    image: node:12-buster-slim
    container_name: weather_comparitor_app
    working_dir: /home/weather_app/
    volumes:
      - ./:/home/weather_app/
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    entrypoint:
      - bash
