[build]
command = "npm run build"
publish = "public"

[context.production]
# Nothing is really different in the production context
# but it's here if it needs to change
# production branch is master
command = "npm run build"
publish = "public
